# If not running interactively, don't do anything
[ -z "$PS1" ] && return

shopt -s autocd

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILE=$HOME/.histfile
HISTSIZE=100000
HISTFILESIZE=100000
#HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

PS1='[\[\033[01;32m\]\h\[\033[00m\]]\$ '
PROMPT_COMMAND='if [ $TERM == "screen" ]; then printf "\ek${PWD/$HOME/~}\e\\"; fi'

if [ -f ~/work/config/alias ]; then
    . ~/work/config/alias
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# environment variables
PATH=/usr/sbin:/usr/bin:/usr/local/bin:/sbin:/bin
if [ -d $HOME/flex ]; then PATH=$HOME/flex/bin:$PATH; fi
if [ -d $HOME/.local/bin ]; then PATH=$HOME/.local/bin:$PATH; fi
export PATH
export EDITOR="vim -u ~/work/config/vimrc"

export CUDA_ROOT=/usr/local/cuda
export LD_LIBRARY_PATH=$HOME/cuda/lib64:$CUDA_ROOT/lib64:$LD_LIBRARY_PATH
export CPATH=$HOME/cuda/include:$CPATH
export LIBRARY_PATH=$HOME/cuda/lib64:$LIBRARY_PATH
export PATH=$CUDA_ROOT/bin:$PATH

if [ -d $HOME/anaconda ]; then 
    export PATH=$HOME/anaconda/bin:$PATH
    export PYTHONSTARTUP=$HOME/work/config/startup.py
fi

function purge(){
echo "sudo aptitude purge $(dpkg -l | awk '/^rc/ { print $2; }' | xargs)"
}

function _expand(){ return 0; }

unset command_not_found_handle

if [ $TERM != "screen" ]
then 
    if [ $(pgrep -xc screen) -gt 0 ]
    then screen -r
    else screen -c ~/work/config/screenrc
    fi
fi
